# Generated by Django 3.1.3 on 2022-03-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bears', '0003_auto_20220315_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='bear_id',
        ),
    ]
