# Generated by Django 3.1.3 on 2022-03-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bears', '0004_remove_sighting_bear_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='bear_id',
            field=models.TextField(default='Null'),
        ),
    ]
