# Generated by Django 3.1.3 on 2022-03-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bears', '0005_sighting_bear_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='deploy_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='recieved',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
