# Generated by Django 3.1.3 on 2022-03-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bears', '0006_auto_20220315_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='deploy_id',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='temperature',
            field=models.TextField(default='Null'),
        ),
    ]
