# Generated by Django 3.1.3 on 2022-03-15 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bears', '0007_auto_20220315_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='bear_id',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='deploy_id',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='recieved',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='temperature',
        ),
    ]
